// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"dependencyInjection/Services/service1"
	"dependencyInjection/Services/service2"
)

// Injectors from wire.go:

func CreateContainer(time float64) Container {
	service := service1.NewService(time)
	service2Service := service2.NewService2(service)
	container := newContainer(service, service2Service)
	return container
}

// wire.go:

type Container struct {
	Service1 *service1.Service
	Service2 *service2.Service
}

func newContainer(Remoteservice *service1.Service, Remoteservice2 *service2.Service) Container {
	return Container{
		Service1: Remoteservice,
		Service2: Remoteservice2,
	}
}
