// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"dependencyInjection/remoteService"
)

// Injectors from wire.go:

func CreateContainer(time float64) Container {
	service1 := remoteservice.NewRemoteService(time)
	service2 := remoteservice.NewRemoteService2(service1)
	container := newContainer(service1, service2)
	return container
}

// wire.go:

type Container struct {
	Remoteservice  *remoteservice.Service1
	Remoteservice2 *remoteservice.Service2
}

func newContainer(Remoteservice *remoteservice.Service1, Remoteservice2 *remoteservice.Service2) Container {
	return Container{
		Remoteservice:  Remoteservice,
		Remoteservice2: Remoteservice2,
	}
}
