// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"dependencyInjection/Services/service1"
	"dependencyInjection/Services/service2"
)

// Injectors from wire.go:

func CreateContainer(time float64) Container {
	sleepService := service1.NewService(time)
	person := service2.NewService2(sleepService)
	container := newContainer(sleepService, person)
	return container
}

// wire.go:

type Container struct {
	SleepService *service1.SleepService
	Person       *service2.Person
}

func newContainer(SleepService *service1.SleepService, Person *service2.Person) Container {
	return Container{
		SleepService: SleepService,
		Person:       Person,
	}
}
